/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./reveal.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#545b6f",
        "secondary-fixed-dim": "#cdd4eb",
        "surface": "#f4f6ff",
        "error": "#b31b25",
        "on-tertiary-container": "#5e6163",
        "on-primary-fixed-variant": "#002a62",
        "on-error-container": "#570008",
        "secondary": "#545b6f",
        "outline-variant": "#a2adc4",
        "inverse-primary": "#4d8eff",
        "surface-container-low": "#ecf1ff",
        "on-secondary": "#f0f2ff",
        "surface-container-highest": "#cdddfe",
        "primary": "#0057bd",
        "error-dim": "#9f0519",
        "primary-container": "#6e9fff",
        "surface-bright": "#f4f6ff",
        "on-error": "#ffefee",
        "on-tertiary-fixed": "#4c4f51",
        "inverse-on-surface": "#929db4",
        "primary-fixed-dim": "#5391ff",
        "primary-fixed": "#6e9fff",
        "surface-container-lowest": "#ffffff",
        "secondary-dim": "#484f63",
        "surface-dim": "#c3d5f8",
        "on-tertiary-fixed-variant": "#696c6d",
        "on-tertiary": "#f2f3f5",
        "on-primary-container": "#002150",
        "secondary-fixed": "#dbe2fa",
        "tertiary-fixed-dim": "#edeef0",
        "inverse-surface": "#040e1f",
        "tertiary-dim": "#4d5052",
        "tertiary-fixed": "#fbfcfe",
        "surface-container": "#dee8ff",
        "surface-variant": "#cdddfe",
        "on-background": "#242f41",
        "surface-tint": "#0057bd",
        "background": "#f4f6ff",
        "tertiary-container": "#fbfcfe",
        "primary-dim": "#004ca6",
        "on-surface-variant": "#515c70",
        "on-surface": "#242f41",
        "tertiary": "#595c5e",
        "outline": "#6c778c",
        "on-primary-fixed": "#000000",
        "on-secondary-container": "#4a5165",
        "on-primary": "#f0f2ff",
        "on-secondary-fixed": "#383f52",
        "error-container": "#fb5151",
        "secondary-container": "#dbe2fa",
        "surface-container-high": "#d5e3ff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
